name: 'Build Directus Backend'
description: 'Build Directus extension and push updated dist'
inputs:
  EXPO_TOKEN:
    description: 'Expo token for dependency install'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Check if running on rocket-meals/rocket-meals repository
      id: repo_check
      run: |
        if [[ "${{ github.repository }}" == "rocket-meals/rocket-meals" ]]; then
          echo "is_main_repo=true" >> $GITHUB_OUTPUT
        else
          echo "is_main_repo=false" >> $GITHUB_OUTPUT
          echo "Skipping backend build - not running on rocket-meals/rocket-meals repository"
        fi
      shell: bash
    - name: Setup Node.js, Yarn & Dependencies
      if: steps.repo_check.outputs.is_main_repo == 'true'
      uses: ./.github/actions/setup-and-install
      with:
        EXPO_TOKEN: ${{ inputs.EXPO_TOKEN }}
    - name: Build the extension
      if: steps.repo_check.outputs.is_main_repo == 'true'
      run: yarn app-backend-build
      shell: bash
    - name: Check if dist has changed
      if: steps.repo_check.outputs.is_main_repo == 'true'
      id: check_changes
      run: |
        if [[ -n $(git status --porcelain apps/backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle/dist) ]]; then
          echo "dist_changed=true" >> $GITHUB_ENV
        else
          echo "dist_changed=false" >> $GITHUB_ENV
        fi
      shell: bash
    - name: Commit and push changes if dist changed
      if: steps.repo_check.outputs.is_main_repo == 'true' && env.dist_changed == 'true'
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git stash --include-untracked
        git pull --rebase
        git stash pop
        git add -f apps/backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle/dist
        git commit -m "Update dist after backend build"
        git push
      shell: bash
    - name: Upload Dist Artifact
      if: steps.repo_check.outputs.is_main_repo == 'true' && env.dist_changed == 'true'
      uses: actions/upload-artifact@v4
      with:
        path: apps/backend/Backend/directusExtensions/directus-extension-rocket-meals-bundle/dist
        name: backend-dist
